### ISSUE TITLE
data documentation

### ISSUE THREAD

**Issue by edvinf** [MikkoVihtakari/BioticExplorer#10]
I have a few remarks about data documentation.

Most fields are implicitly defined by the data documentation for the NMDbiotic, but that is not made explicit in the documentation on astarte. I think it would be very useful to provide a link so that users are aware of that documentation.

A few fields are merged in from other sources, and are left undefined even for users aware of the connection to the NMDbiotic documentation. I do not expect I have a complete overview of those, but I have noticed the (rather useful) variable 'gearcategory'. I think users need information about how this variable is derived.

**Comment by MikkoVihtakari** [comment]
Apart from a few added/modified categories (such as cruiseseries, gearcategory, stationstart/stopdate to POSIXct) the fields are documented here which is linked in the app (Cog -> Data fields): http://www.imr.no/formats/nmdbiotic/v3/nmdbioticv3_en.html

This should suffice for the purpose for now. Reopen if you disagree.
