### ISSUE TITLE
NaN for lat long

### ISSUE THREAD

**Issue by edvinf** [MikkoVihtakari/BioticExplorer#2]
When loading a data set with some positions not filled. The bar for filtering on Latitdue and Longitude gets stuck at a minimal value called "NaN".

Tested on http://astarte.imr.no/shiny/ via Safari on Mac. For reference the data set was called "commSampling2018_2019_03_31.xml" and can be provided upon request if needed to reproduce the issue.

**Comment by MikkoVihtakari** [comment]
Please try to the desktop version and see whether you can reproduce this issue. I tried to fix this during the latest commit.

**Comment by edvinf** [comment]
Thanks. I confirm that this works fine in the desktop version.
