### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by edvinf** [MikkoVihtakari/BioticExplorer#3]
I think it would be nice to have a link to field documentation on http://astarte.imr.no/shiny/. Fields mainly follow biotic3, which is documented at http://www.imr.no/formats/nmdbiotic/v3/.

A few fields has configurable units in bioticexplorer, which can make them deviate from documentation. I think this should be clearly documented in the data. I would prefer for such conversions to be highlighted by introducing them in new columns. E.g. 'individalweightGrams'.

Tested on http://astarte.imr.no/shiny/ with Safari on mac.

**Comment by MikkoVihtakari** [comment]
Added a link to the documentation in https://github.com/MikkoVihtakari/BioticExplorer/commit/3b6bb073e34233a90ea50ee6653a73163d046cab
